---
kind: pipeline
name: fossa

steps:
- name: fossa-analyze
  image: rancher/drone-fossa:latest
  failure: ignore
  settings:
    api_key:
      from_secret: FOSSA_API_KEY
    debug: true
  when:
    instance:
      - drone-publish.rancher.io
    ref:
      include:
        - "refs/heads/*"
        - "refs/tags/*"
        - "refs/pull/*"
    event:
      - push
      - tag

- name: fossa-test
  image: rancher/drone-fossa:latest
  failure: ignore
  settings:
    api_key:
      from_secret: FOSSA_API_KEY
    command: test
    debug: true
  when:
    instance:
      - drone-publish.rancher.io
    ref:
      include:
        - "refs/heads/*"
        - "refs/tags/*"
        - "refs/pull/*"
    event:
      - push
      - tag

- name: fossa-test-alt
  image: rancher/drone-fossa:latest
  failure: ignore
  settings:
    api_key:
      from_secret: FOSSA_API_KEY
    command:
      - test
    debug: true
  when:
    instance:
      - drone-publish.rancher.io
    ref:
      include:
        - "refs/heads/*"
        - "refs/tags/*"
        - "refs/pull/*"
    event:
      - push
      - tag

---
kind: pipeline
name: docker

steps:
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: rancher/drone-fossa
    tags: latest
  when:
    instance:
      - drone-publish.rancher.io
    ref:
      include:
        - "refs/heads/*"
        - "refs/tags/*"
        - "refs/pull/*"
    event:
      - push
      - tag

