---
kind: pipeline
name: fossa

steps:
- name: fossa-analyze
  image: rancher/drone-fossa:latest
  failure: ignore
  settings:
    api_key:
      from_secret: FOSSA_API_KEY
    debug: true

- name: fossa-test
  image: rancher/drone-fossa:latest
  settings:
    api_key:
      from_secret: FOSSA_API_KEY
    command: test
    debug: true

---
kind: pipeline
name: docker

steps:
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: rancher/drone-fossa
    tags: latest

